### ISSUE TITLE
[Hood of the Defiler] Logic of stacks actually bugged, but can we keep it and change tooltip instead?

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1048]
Enemies hit by @Ability2 receive a debuff that reduces CURRENT armor by 15%, and additionally take 25% increased physical damage from all sources. Stacks up to 5 times and lasts 9 seconds. Increases attack damage by 0.5% for each target hit, up to 100 stacks.
--
What actually logic is:
 local additionalArmorLoss = math.ceil(victim:GetPhysicalArmorValue()*0.15)
    if origStacks < 5 then
        additionalArmorLoss = 0
    end
"modifier_hood_of_defiler_armor_loss"
			{
				"IsDebuff"	"1"
				"IsHidden"	"1"
				"Properties"
				{
					"MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS" "-1"
				}
			}
Each hit applies a stack to the target, up to 5.
All stacks (1,2,3,4 or 5) actually add only -1 armor.
Each additional hit after you reach 5 stacks (becaue if origStacks < 5 then you reduce 0 additional armor) now will reduce current armor by 15% each hit, achieving 90% reduction in 29 additional hits, and further beyond up to 99.(9)%.
This is actually really fine mechanics which allows to deal with insane numbers of armor you created by paragon, serengaard and passive armor amplifiers.
This can place Zhonik's head piece because of his physical W and autoglyph, but other effects are essentially useless, attack damage roll barely adds 1/4, post-mitigation doesn't affect total post-mitigation given by E3, 50% attack damage is low.
Initially item itself could add x6.75 total multiplier (and another x9.1 from Demon), but it's not possible in any of current situations. Demon damage roll is useless, because all Demon abilities we have are placed on Cherno, who has already good elemental amp and Ekkan, who won't equip this helm just to buff Q.
So on current zhonik he will add only about x1.5-2 of total damage increase (depending on initial attribubtes) + armor piercing. Since it has no runes, I ask permission to buff it to 1% per stack so total multiplier will be about x2-2.9 and change tooltip correlating to actual effect.

Enemies hit by @Ability2 receive a debuff that increases incoming Post-Mitigation physical damage from all sources, stacks up to 5 times and lasts 9 seconds. Once max amount of stacks reached, each consecutive hit with @Ability2 will decrease current armor of target by 15%. Additionally each target hit adds 1% of Bonus Attack damage, up to 100%.

**Comment by redledcat** [comment]
That's good alternative to marauder gloves as armor shred effect, but helm itself usually give pretty high damage output, or in case of Colossus, also survivability. 
Actually, 1% is not enough.
![20190227143752_1](https://user-images.githubusercontent.com/32621322/53488029-316d4800-3a9e-11e9-9c1f-ed6c991ca91e.jpg)
![20190227144323_1](https://user-images.githubusercontent.com/32621322/53488031-33370b80-3a9e-11e9-9228-8fff027f913e.jpg)

**Comment by DeckardCainRPC** [comment]
i just read the logic error breakdown, and i think this is funny as hell. good find

**Comment by Nintai** [comment]
Well, except that its wrong.

Lets go through it.
![image](https://user-images.githubusercontent.com/5485559/53507285-e6f8c500-3ab7-11e9-868c-d87479c61c62.png)


This line here is just the VISIBLE modifier, that is shown on the enemy, it can have count from 1 to 5:
![image](https://user-images.githubusercontent.com/5485559/53507334-fbd55880-3ab7-11e9-8e15-ccaa77a98140.png)


This here is the INVISIBLE modifier, that actually reduces the armor. In the first line we are getting the current amount of reduction. In the second line we are getting the CURRENT armor of the enemy (means if he normally has 3000 and has -1500 from some debuff, the current armor is 1500).
The bug is actually in the third line, which should be `if origStacks >= 5 then` to ensure that u dont reduce armor when there are already 5 stacks.
In the last 2 lines we are adding stacks to the invisible modifier equal to the amount of armor that should be reduced, if its 1000 base armor, it would be 150 stacks with 1 visible stack
![image](https://user-images.githubusercontent.com/5485559/53507574-6e463880-3ab8-11e9-9d07-5736e1f2a108.png)



so yeah, the bug is: armor reduction is 0 for 1 to 4 stacks, and 15% for the 5th stack

**Comment by Nintai** [comment]
Alright, seems the bug is:
Stacks 1 to 4 do NOTHING except reducing -1 Armor on all stack amounts
Stacks 5 to infinite reduce armor by 15% until 100% is reached

Gonna fix that ;)

**Comment by Nintai** [comment]
Fixed that some time ago 😛
