### ISSUE TITLE
Astral Ranger R2 tooltip lacks damage type information

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1112]
it says the quakes deal x% of R1's damage, however it doesn't specify if it's Base Ability: R, or if it's Pure damage, or Cosmic element. it should specify all of those things if applicable

**Comment by redledcat** [comment]
well I intentionally deleted it, because it can confuse player with ability augments, which **additionally** multiply initial value, while R2 doesnt, it just incereases R1 by said % value.
So if it will state base ability and element it would be logical to treat it as additional multiplier which does respect both.

**Comment by DeckardCainRPC** [comment]
okay, so if i understand this correctly,

1. R2 does not actually deal an instance of damage on its own?
2. R2 simply increases the damage of R1, and also causes each R1 star to deal its damage in a small area around the target?

**Comment by redledcat** [comment]
1. yes
2. yes, indeed

**Comment by DeckardCainRPC** [comment]
fantastic, then here's a new tooltip for it which clarifies the issue:

"Increases the damage of [R1]. Each star also slams the ground on impact, dealing its damage in a small area around the primary target and stunning all affected enemies for 0.03 seconds."

**Comment by redledcat** [comment]
closing because everything was updated
