### ISSUE TITLE
Omniro still has issues

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1166]
1. Ghost's Orb effect still says the cloud lasts 400 seconds
2. add the following sentence to R's tooltip: "Each of these attacks will not consume elemental charges."
3. a discord user said that the first attack during R WOULD consume a charge, but that each of the remaining attacks would not consume charges. verify this
4. all of his fucking attack passives AND orb effects interfere with puzzles
5. ALL OF HIS FUCKING **EVERYTHING** INTERFERES WITH PUZZLES (and this includes the Redfall Castle Warlock boss's spheres)
6. his runes really do count as Base Ability Damage for the appropriate skill tree - some of his passive Omni Mace effects trigger Guard of Luma and Demon Mask, for example - and this information should be added to the rune tooltips
7. his element roulette UI is still overlapping the top of NPC dialogue boxes
8. Wind's Orb effect is fucking insufferable and i beg you to change it. constantly pushing monsters away is fucking annoying even on ranged heroes, and the fact that it FREQUENTLY pushes mission-critical monsters behind inaccessible terrain is just untenable
9. Ice's Mace effect tooltip says it deals an instance of damage, but the tooltip doesn't tell you how much
10. Nature's Mace effect tooltip scaling info says "something something BASED" and then gets cut off

**Comment by redledcat** [comment]
A lot of tooltip lines which are longer than about 26-28 symbols being cut.

**Comment by redledcat** [comment]
Wind orb indeed is cancer in serengaard map because I pushed a pack of monsters on bottom line to the abyss, and can't hit them anymore

**Comment by redledcat** [comment]
1 - fixed
2 - fixed
3 - no
4 - pretty sure it's all right
5 - pretty sure it's all right, ok it'll check spheres right now
6- mace counts as Q, orb counts as W
7 - fixed also doesn't overlap anything in game except Chat because it's not custom UI and doesn't have z-index to define it's height so it's always lower than any other custom HUD implemented what a wondrous world we live in
8 - fixed
9 - it's "additional instance of Omni Mace", which is currently 4-10% of your attack damage base
10 - probably fixed with correct wording because it was too long line

**Comment by redledcat** [comment]
Yep redfall puzzles are fine, I'm closing the issue
