### ISSUE TITLE
Umbra says Iron Colossus is increasing Omniro's E1 damage

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#1198]
i would investigate it but i am
1) on drugs
2) don't care

ADDENDUM: i'm not high, i'm just on soporific (sleep-inducing) medication and re-writing a tooltip just isn't on my list of things i'm willing to do atm

**Comment by TotallyAFlareon** [comment]
![image](https://user-images.githubusercontent.com/48076610/59005876-423fff00-87ed-11e9-85d3-a4ce88dc69a1.png)
So, on test perfect rolls. 
![image](https://user-images.githubusercontent.com/48076610/59005926-76b3bb00-87ed-11e9-8e0c-fa36f1e7353c.png)
Still on test, no helm.
![image](https://user-images.githubusercontent.com/48076610/59005936-816e5000-87ed-11e9-9c4b-8566f09f7dde.png)
On test, using another helm with the same kind of str rolls to keep firelock at it's high %

It seems like, Iron colousus is boosting all physical damage, and not just the damage from autoattacks, or as it's seen to be, it's own damage, because it is also tripled with echo gloves.

**Comment by DeckardCainRPC** [comment]
yeah iron colossus deals an instance of Physical Normal damage, it is a damage-dealing item. that much i can say for sure.

what remains is, i don't know whether it *is* or whether it *should* boost ALL physical damage

**Comment by Nintai** [comment]
It seems u guys forgot that Q deals dmg based on attack damge (35% on lvl 7) which is ofc boosted by iron colossus because it gives 10x ur str as attack dmg

Thats why the e+8 that u see in the screenshots is the Q effect of lightning (CURRENT HP % DAMAGE) while the e+7 and with iron colossus e+11 (because u get 493k more attack dmg which is *4.93e3 more dmg) is the normal Q effect of 35% of attack dmg as lightning dmg.
