### ISSUE TITLE
[Winterblight 2.0] Tiamat boss is too heavy for our PC configurations

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#1269]
100% of discussions about Tiamat include facts it crashes, lags, sometimes freezes the game once she starts her fire session.
I think it's based off Dinath Q, which is also super laggy even using few Q areas.
In case of Tiamat you have solid 8 screens of flaming ground, which kills perfomance and makes fight several steps more difficult.
Please rework it and redo into something less fancy, but possible to beat for each player.
Winterblight 2 is already a challenge for PC, some mobs create huge amoun of particles and sounds, such as "return" types exo-eidolon or ogre armor, this "damage negation" thing from dragoons, which creates a sound event for each damage taken outside of radius, Hell on Ice is just literal hell, AA drop FPS to 0 in matter of second.

**Comment by DeckardCainRPC** [comment]
imo, rework Dinath's Q to be more like Jakiro's Liquid Fire (E spell). it should still be ground-targeted, but instead of leaving a laggy thinker unit on the floor, it just applies a stacking DoT debuff to any enemy units within its radius when it impacts the ground. q1 should then be modified to apply the movespeed slow to anything affected by the burn debuff, q2 duration should then be modified to increase the duration of the burn debuff itself, q3 is then "apply a stack of the burn debuff to everything within like 300 range of Dinath as she flies to the target point", and q4 is just as self-explanatory as q1 and q2. each stack of the burn burn debuff should deal damage independently, just like the newly revamped Crown of the Ruby Dragon.

**Comment by redledcat** [comment]
wait I fixed it a while ago
no more logariphmic generation of particles because it was creating N projectiles for each current hero unit on map, launch it multiple times like every second, until target is dead
ofc fire flames also are pretty unfriendly to game perfomance but at least it's totally playable now
