### ISSUE TITLE
wb skull ring

### ISSUE THREAD

**Issue by ChalkyBrush** [ChalkyBrush/roshpit-bug-tracker#1298]
locking glyph slot on property1 will still change hero requirement

**Comment by DeckardCainRPC** [comment]
explanation, for those who aren't aware of this item's history, but are still interested:

Winterblight Skull Rings have a random glyph property as their slot 1 roll. if they are generated with a hero-specific glyph, as opposed to a general-use or "neutral" glyph, the ring is updated at that time to be hero-specific as well - this places the hero's name in the bottom-right corner of the item's tooltip.

for a very long time (over 2 years i think!), the server's "form" for handling save/load requests did not actually handle the hero-specific flag if it appeared on trinkets. this meant that you could very easily remove a Skull Ring's hero-specific flag by depositing it into your Stash, and then withdrawing it; the rest of the ring's data would be intact and functional, but the fact that it was hero-specific was not retained during the save process, because the server never recorded it.

to my knowledge, i am the person who first discovered this bug, and i deliberately did not (formally) report it as an issue, since the rings were only available for a very short window of time (an old Winterblight global event, built in a week to sass Volvo's shitty winter-themed event for Dota 2 that year), and were generally considered uselessly weak anyway. i considered it an amusing bug, but also an important debugging tool, since certain glyph effects could be used on normally-inappropriate heroes in order to cause certain types of mayhem in the game that would be difficult or impossible to set up during "normal" gameplay without the assistance of console commands; for example, Paladin's Glyph of Zeal, which causes 40% of his attacks to generate a free strike against another enemy unit within his attack range, was useful for testing certain server-crashing conditions. another example is my discovery that one of Venomort's old glyphs, the notorious "every hit generates a free attack on the same target" one (which no longer exists), would always cause a server crash when equipped to melee heroes - that glyph's script would attempt to call the attacking unit's projectile data, but for melee heroes, no such data existed, resulting in a crash.

anyway, with the advent of Winterblight's new dungeon came the return of Winterblight Skull Rings, now available as common drops from various enemies there. this meant that the time had come for me to (formally) report it as an issue, and it was fixed very quickly.

that *specific* issue, mind you. a veteran player named vietboi was fucking around one day, rerolling a Skull Ring, and he discovered that locking property1 (the slot which rolls a random Glyph effect) will prevent that property from changing, as intended... however, the code which determines whether or not the ring should have a hero-specific flag set still runs, and instead of looking at the newly-locked property, it uses the data for whatever Glyph property would have been generated for the ring **IF** the player hadn't locked that slot.

so, at time of writing, you could have a Paladin-only Glyph property in slot 1, then lock that slot and reroll. you would then observe that the hero-specific flag is very likely to have changed, or disappeared entirely if the game would have generated a Neutral Glyph property if you hadn't locked the slot. in this way, it is entirely possible to create Skull Rings that have valid, but incorrect, hero-specific flag data, and because of the fix to the original issue i detailed above, this flag will be dutifully saved by the server and will persist even after depositing and withdrawing it again. got a Paladin-only Glyph on a ring that says it's for Axe only? no questions asked, item saved!

alas, even after multiple years have passed, and fixes have been implemented, mortals are powerless to keep me from putting my Skull Ring on whoever the fuck i want to. god bless america.

**Comment by ChalkyBrush** [comment]
fixed in 4.0
