### ISSUE TITLE
[4.1] The game still refer Eternal Forest Striders as red_october_boots

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1520]
begone 3.9

**Comment by DeckardCainRPC** [comment]
not a bug. changing an item's internal name - which is never displayed to the player, and is only used in the game's code - will absolutely break the game, which is why Soul Ring was split off into Neverlord's Soul Ring when it was remade, and why Claw of the Dead is still known internally as ``boneguard_gauntlets`` https://www.roshpit.ca/items/item_rpc_boneguard_gauntlets
