### ISSUE TITLE
Astral Ranger W arcana eats her mana per arrow shoots, not on cast. Instantly empty her mana regardless

### ISSUE THREAD

**Issue by TheVietboi** [ChalkyBrush/roshpit-bug-tracker#1582]
if it's intended, then it should be changed as well

**Comment by DeckardCainRPC** [comment]
~~the entire thing sucks and will have to be completely redone anyway.~~ i had intended for it to sort of emulate a Bowazon's Strafe spell from D2 but it doesn't. it's a very convenient delivery system for q2, because it can condense about 7 seconds worth of autoattacking into 0.75 seconds, but its w1 isn't especially good compared to other runes in RPC and its w3 is outright bad.

**Comment by redledcat** [comment]
mana cost singnificantly reduced next patch

**Comment by redledcat** [comment]
But mana drain itself can't be removed while saving "on-cast" trigger effect (without remaking whole ability in lua)
