### ISSUE TITLE
Axe Arcana memory leak

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#256]
some effect belonging to his arcana spell gradually causes performance issues as the match progresses. i have no further information that might help narrow down what specific element/particle is causing it

**Comment by StillStealSteel** [comment]
A lot of particles should be already removed from rpc.
Geode especially on axe and necro, bahamut body arcana, stormcrack on axe cause huge fps drops after 15 of gameplay.
Isn't sounds enough at least for geode to understand when it does amp damage.

Even 'r_particle_min_timestep' isn't helpful.
Try use necro Q or necro arcana Q on clockwerk cogs at sea = 1 fps at best.

**Comment by redledcat** [comment]
plz

**Comment by redledcat** [comment]
h u r t s
![20180813003100_2](https://user-images.githubusercontent.com/32621322/44006738-2360774e-9e92-11e8-9748-ac29b9d49200.jpg)

[crash_dota2.exe_20180813003151_1.zip](https://github.com/ChalkyBrush/roshpit-bug-tracker/files/2281373/crash_dota2.exe_20180813003151_1.zip)

**Comment by redledcat** [comment]
https://youtu.be/TCd5uLY9EW8
that video shows how fast and inevitably fps drops

**Comment by redledcat** [comment]
WELL
good news: it's less destructive to our PCs now, fps drop remains, but it's now much much better with same experiment settings.
bad news: it's still leaks memory, and client death just delayed, but not prevented, and super bright white parcticle seems to be an artifact, because look:
![20180817210226_3](https://user-images.githubusercontent.com/32621322/44281582-f5d90200-a260-11e8-8bd1-c2d5f701f848.jpg)
![20180817210225_2](https://user-images.githubusercontent.com/32621322/44281603-05f0e180-a261-11e8-9a94-40c2e46b8a46.jpg)

**Comment by redledcat** [comment]
and yeah, each cast eats fps for several seconds after every particle from arcana is gone. check if some of them do not destroy properly

**Comment by redledcat** [comment]
new video (can be still in processing, YT has issues)
https://youtu.be/GHsBSmbAiAs
main things described in previous two comments, but again
1)it's better
2)still lags a bit even solo, you can check fps meter how big is a difference
3)partial log
[log.txt](https://github.com/ChalkyBrush/roshpit-bug-tracker/files/2298264/log.txt)
4)white particle going crazy
5)note: fps is back to 170 after spam finished and turned off obs

**Comment by DeckardCainRPC** [comment]
at long last, this one got fixed
