### ISSUE TITLE
Sorcerer's W3 aura of mana drain

### ISSUE THREAD

**Issue by hodor02** [ChalkyBrush/roshpit-bug-tracker#3]
Sorcerer's W3 gives players intel when they are in range of her aura. When a hero has lower intel than her and moves out of range of her aura all the mana is drained from that hero. I don't know if this can be fixed or not.

**Comment by redledcat** [comment]
Let's think about possible solutions, because Valve won't do that work for us, it's part of Dota mechanics.
First and easiest solution is making W3 aura global, such as Dota CM. If its considered too op, then I have that solution: let it stack up when hero is in range, 10 stacks, 1 stack per second. Stacks run out when buffed hero dies. That makes 90s period (first stack applies immediately) of "charging" a hero with additional INT, and then CM can go do her own work on map, i.e. clearing wave in serengaard (boosting a trapper). But if charged hero dies, she has to do it again (which is really likely to happen in serengaard trapper because of aggressive units and return damage, unless there is auriun - that will take 3 slots to maximize Trapper potencial, and leaves only 1 hero slot for phys/pure carry, probably still never happen)
1) There won't be a factor which suddenly decreases int value and draining whole mana out of pool.
2) There is no "full support" build for CM which means she can't focus gameplay only on being near certain hero-carry, more likely CM will just solo her part of map.
3)Best usage of W3 I've ever seen is boosting trapper in serengaard, and even in that case CM does not really exceeds utility of Zeus as support or carry. Perma BKB is the criterion which separates full magical heroes and pure/phys carries.

**Comment by StillStealSteel** [comment]
Isn't this fixed? I thought it is with chalky's big update on custom attributes.

**Comment by Nintai** [comment]
Just tested it, upon losing the W3 aura, u will keep the % of max mana u currently have
With Aura: 2000/5000 -> 40%
WIthout: 200/500 -> 40%
