### ISSUE TITLE
non-English curated items on roshpit.ca.

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#31]
Curating items with non-English account leads to curated item page broke. (or even being unaviable)
Eye of Avernus
![avernus](https://user-images.githubusercontent.com/32621322/31579398-acc2f584-b135-11e7-9071-906bb33d1fb9.PNG)
Ruinfall Skull Token
![ruinfall token](https://user-images.githubusercontent.com/32621322/31579406-c4cf7346-b135-11e7-9617-644de5f94438.PNG)
Magebane (they have now only 2 of each property variance curated)
![magebane](https://user-images.githubusercontent.com/32621322/31579413-e29893a8-b135-11e7-8862-300cba062eea.PNG)
Twilight
![twilight](https://user-images.githubusercontent.com/32621322/31579422-18f0682c-b136-11e7-80b0-63d7b534696b.PNG)
etc etc etc.

**Comment by StillStealSteel** [comment]
It's easy to filter this in database to validate allowance of non-english characters. Chalky should implement this from the beginning.
Or even implement something like language switch, so you can see items only in selected language. But it require more work that are not so useful. Site in english more then enough.

**Comment by ChalkyBrush** [comment]
They are already stored seperately, and it defaults to english IF it is there. If there is no english, it looks for russian, and no russian it looks for chinese.

So the lack of information is because there isn't enough curating on english clients.

The plan is to allow people who log in an option to select their language preference
