### ISSUE TITLE
Sturdy Centaur Horns stat generation is abnormal

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#318]
first, it's important to note that Sturdy Centaur Horns is the only immortal item whose special effect appears in slot 4, rather than slot 1 or, far more rarely, slot 2 (i can only think of Cap of Wild Nature as an example, and even then it is guaranteed to have a special effect appear in slot 1). because slot 4 often has a maximum attribute value greater than earlier slots, this distinction alone does slightly reduce the potential of Sturdy Centaur Horns to have high rolls.

furthermore, i have seen multiple users report extraordinary results when trying to reroll the damned things, and i have confirmed these results myself. evidently, even a level 100 pair of Horns will routinely generate double-digit attribute values in its available slots. therefore i have a strong suspicion that, given the age of the item and its unique slot 4 status, the Horns are the victim of a bizarre corner-case in stat generation that is not experienced by any other item.

**Comment by redledcat** [comment]
AND I HAVE AN ASWER NOW @DeckardCainRPC 
due to function
`RPCItems:RollAttribute(xpBounty, 1, 3+bonus, 0, 0, item.rarity, false, maxFactor*10)`
which rolls all the attributes in this property, max possible roll is fully depends on 3rd value here, "3+bonus". Max roll of `maxfactor*10 `is reacheable only in really wet dreams because in fact, 3+bonus is equal 7.
Max possible value here is strictly based on this and is` 5*7*80=2800`, and happens in unbelievably rare case scenario. Max roll `300*10=3000` exists only for trolling poor in math souls as I am.

**Comment by redledcat** [comment]
it's same for volcano orb
What a great lie to the whole world

**Comment by redledcat** [comment]
NO MORE
