### ISSUE TITLE
Chernobog

### ISSUE THREAD

**Issue by Jakunazuta** [ChalkyBrush/roshpit-bug-tracker#337]
If you die as Chernobog the stats of W4 get disabled until you activate your W ability again(whilst using the level 75 Glyph that gives you all passive/actives without using the skill).. Idk if that's intended but it seems weird and it can pick you off guard if you don't have that extra strength/agility

**Comment by DeckardCainRPC** [comment]
hi, if you're going to continue to submit bug reports to the tracker, please make the titles more specific - simply reporting a bug called "Chernobog" doesn't tell us what's wrong, doesn't help us categorize it, and makes it impossible to refer back to it in the future.

w4 is handled as a buff, one which doesn't persist after death. this is working as intended, because when you respawn, W will ALWAYS be in the OFF state, meaning there's no reason for the ON-state buff to persist after death (you won't respawn with it ON). the simplest way to not get caught off-guard by this functionality is to just toggle W when respawning, which isn't too obtrusive considering nearly all chernobog builds always leave it toggled on anyway.

**Comment by ChalkyBrush** [comment]
this is intended
