### ISSUE TITLE
item bug and gone

### ISSUE THREAD

**Issue by panduharrien** [ChalkyBrush/roshpit-bug-tracker#339]
i forget if my pass is over. then i load my character from premium slot.
after i equip my item and i would to sava the character, it cant coz its not premium anymore.
so i buy the pass with. then my chart inventory goes blank, and i cant open save on oracle.. so my item gone.
please give it back

**Comment by DeckardCainRPC** [comment]
we cannot restore items to your account, because no record of them exists. there are no server logs that keep records of items being added, removed, or changed, because we are not EA or Ubisoft, we simply don't have the money or the storage space to support that level of transaction logging.

if it makes you feel any better, this problem, "my pass expired and I didn't know," has affected everybody at some point. we've all lost important items to it. you just have to be careful in the future.

**Comment by panduharrien** [comment]
okay its okay, and today can't save the game, just wanna report that,
please fix thx :)
