### ISSUE TITLE
Zhonik's Arcana E keeps disappearing for no reason.

### ISSUE THREAD

**Issue by FortuneReborn** [ChalkyBrush/roshpit-bug-tracker#39]
Title, not much more I can say about it, it keeps happening to a friend of mine, it causes him to lose all his stacks, which take some time to build, and the issue is immensely frustrating.

**Comment by StillStealSteel** [comment]
Can confirm this. Not so often but it can dissapear.

**Comment by SilentC** [comment]
Can also confirm this. Seems to happen when taking aoe dmg like from treant boss in redfall.

**Comment by redledcat** [comment]
For me it happens completely randomly, with no links with incoming stuns, damage, buffs and debuffs, maps etc.
Sometimes several times in a row, like 4s duration sphere and 2s next sphere.
But there are no thoughts how to reproduce it with high chance.

**Comment by FortuneReborn** [comment]
My friend has it even out of combat sometimes, it is not linked to enemy AOE abilities.

**Comment by redledcat** [comment]
@ChalkyBrush that could be linked with stuns Zhonik receives. 
Have a lot of disappeared E in 
1)Ghost of Perdition battle, which coldsnaps me 
2)Alchemist battle, where moving traps stun me
3)Redfall bombers zones
But it does not affect current E, instead it affects next several E spheres.

**Comment by StillStealSteel** [comment]
The bug is still there.

Checked source code by myself, but it is hardly to understand where problem can be.
As temporal solution i suggest to prolong E3 stacks for 4-5 seconds, so you can cast another one E and do not lose stacks (do not increase them just keep them at the same stacks when you leave or field dissapear for no reason). Because you can receive 80% reduction on next E cast, but you lose all your E3 stacks - and it is really hurts gameplay with arcana right now.
What do you think?

**Comment by redledcat** [comment]
It's not connected with any stuns, gear, enemies, maps, terrain stuff.
I only can think that could be Zhonik position in the start of cast and cast vector

**Comment by redledcat** [comment]
Bavibi gj
