### ISSUE TITLE
[Ground event] That button randomly fails to work

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#452]
Several reports so far for that particular button
![bugged](https://user-images.githubusercontent.com/32621322/38084519-7a6675a8-334d-11e8-9618-1303b4c98c76.png)
![unknown 2](https://user-images.githubusercontent.com/32621322/38084521-7ada8402-334d-11e8-8184-37573fddd6f7.png)

**Comment by DeckardCainRPC** [comment]
where are those pesky plumbers when you need them

**Comment by redledcat** [comment]
Burnt out at work

**Comment by DeckardCainRPC** [comment]
@ChalkyBrush just making you aware of this, it's actually become a serious issue instead of a humorous "blooper"-type accident. this button apparently fails to function nearly 50% of the time, for unexplained reasons. if you need more information i'll see if i can dick around and come up with something concrete but it doesn't appear to be specific to any hero model or sequence of events or anything else

**Comment by ChalkyBrush** [comment]
should be fixed now
