### ISSUE TITLE
Double pick of Arkimus + Slipfinn bugs skills for one of them

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#469]
Channel goes as usually, but after successful end of channel he does not "jump", neither apllies any buffs.
Map and gear does not matter.

**Comment by redledcat** [comment]
I got it now

**Comment by redledcat** [comment]
> oscarxf -
fisherman and  Arkimus
once choose fisherman and  Arkimus together， Either Arkimus's R does not come out, or the fisherman 
redledcat - 03/14/2018
double pick of Arkimus and Slipfinn causes skill bugfisherman and  Arkimus
once choose fisherman and  Arkimus together， Either Arkimus's R does not come out, or the fisherman 
redledcat - 03/14/2018
double pick of Arkimus and Slipfinn causes skill bug <

**Comment by redledcat** [comment]
I think it depends who picks hero first.
I've picked after Slipfinn so my AM got R bugged.

**Comment by bavibi** [comment]
There are several functions called "jump_start" across the code. May this happen because of it?

scripts_roshpit\vscripts\heroes\antimage\machinal_jump.lua:
    1: function jump_start(event)
    2  	local caster = event.caster
    3  	local ability = event.ability

scripts_roshpit\vscripts\heroes\monkey_king\monkey_jump.lua:
   14  end
   15  
   16: function jump_start(event)
   17  	local caster = event.caster
   18  	local ability = event.ability

Desktop\scripts_roshpit\vscripts\heroes\monkey_king\year_beast.lua:
  429  end
  430  
  431: function jump_start(event)
  432  	local caster = event.caster
  433  	local ability = event.ability

scripts_roshpit\vscripts\heroes\slark\jump.lua:
  156  end
  157  
  158: function jump_start(event)
  159  	local caster = event.caster
  160  	local ability = event.ability

scripts_roshpit\vscripts\worlds\winterblight\monsters\winter_monsters.lua:
  183  end
  184  
  185: function jump_start(event)
  186  	local caster = event.caster
  187  	local ability = event.ability


both archon_form and bubble_possession use jump_start

**Comment by ChalkyBrush** [comment]
never realized this was a problem (repeating function names)
I will change the names so they are all unique then. Thanks!

**Comment by ChalkyBrush** [comment]
fixed for next patch (assuming this is the problem but it seems likely)

**Comment by redledcat** [comment]
Seems to be fixed. Tho oscarxf still says it's bugged with pit weapon of slark. Have not found this myself.
