### ISSUE TITLE
lost items

### ISSUE THREAD

**Issue by meruzhetti** [ChalkyBrush/roshpit-bug-tracker#485]
after dota crash my few items was losted. what i should do?

**Comment by DeckardCainRPC** [comment]
this bug tracker is for reporting bugs with Roshpit Champions only. we cannot provide technical support for any problems with your PC, or memory crash issues in Dota 2.

item data is only saved under the following conditions:

1. **Chiseling to unequip the item at the Blacksmith** performs an automatic hero data save.
2. **Saving your hero** will save the data of all of their equipped items.
3. **Moving an item INTO your Pool of Eternity stash** will save its data. _Removing an item from the stash does not save it._
4. **Items sold or purchased on the Market are saved.**

if none of these things happen to the item, then we have no record of it.

because Roshpit Champions is a low-budget game with 1 programmer living in a garage in Canada, we do not have the finances or the infrastructure to support item database transaction records. large companies like Blizzard can afford to store 48TB of item transaction logs going back 11 years, but we cannot.

**Comment by redledcat** [comment]
Probably it's time to finally return these items to the poor guy
