### ISSUE TITLE
Elemental Warlord's R1 (pulverizer) Doesn't work on fully magic immune enemies

### ISSUE THREAD

**Issue by nedamettin** [ChalkyBrush/roshpit-bug-tracker#490]
Not completely tested but I can kill anything besides zombies with full magic immune in Serengaard because R1, the main damage dealer rune doesn't work even though it is physical. My other proof is that I can't see the visual effect of R1 on zombies but anything else.

**Comment by nedamettin** [comment]
i suppose somebody else reported this before (i just saw while browsing previous posts) so.. there's that

**Comment by redledcat** [comment]
Whirling Flail (dusk q) is physical
Cataclysm (dk R) is pure
Voltex R is pure
Red General skull basher (Q) is physical
His E is physical too
His arcana is pure
Drow's astral rift and celestial burst (e and r) are pure
Epoch Guardian has pure R
Paladin's R3 is pure
Sorc's pyroblast is pure
Shadow Aspect E4 is bugged (and pure) (and also attack modifier as R1 of warlord in thread head)
Seinaru's Odashi leap is physical
his E1 and E2 are physical
Elemental Warlord's axes are physical and have pure component from W4
Slardar's W1 is physical and also a cleave
Cherno R3 is pure
Venge has two pure layouts of spells
Arkimus has body which converts all damage to pure, but most of skills do not start to pierce BKB because they are not intended to pierce it.
Bahamut's body R is pure too.
probably missed some arcana effects
etc etc etc
ALL of these spells do not pierce magic immunity and never pierced.
if something does not pierce BKB it's like to just being intended.
But actually it would be perfect to have official announcement is there a spell or rune which is meant to pierce and which are not intended. @ChalkyBrush 
That would simplify answers for these threads to just "this is intended, that's all"

**Comment by redledcat** [comment]
Also, in Dota 2 it's not obligatory being pure/physical and pierce BKB at the same time.
I know R1 warlord seems to be able kill bkb stuff with that, because it's attack modifier, but yeah, that's not a fundamental truth.
Echo Stomp, Purification, Tree Throw, Slithereen Crush, Brain Sap (without agh), Mist Coil, Glaives of Wisdom( without agh, and **they are attack modifier too**), Arcane Orb (which is attack modifier too), Macropyre (without agh) do not pierce BKB too being pure or physical natively.

**Comment by nedamettin** [comment]
a skill that is based on attack power and purely physical and not targeted, in my opinion should pierce the immunity. if this was not a huge issue for the character, i wouldn't have posted it, yet EW's builds focus only  on a single damage type, which means it is a huge problem for EW.

if it is intended, i think it shouldnt be

**Comment by DeckardCainRPC** [comment]
it's essentially a cleave effect, not too different from Hydroxis W1 and R3 (which both pierce Spell Immunity). i agree that BM's Arcana R1 should probably pierce Spell Immunity too, and that's my vote.

**Comment by ChalkyBrush** [comment]
i'm leaning towards this as well which is why I haven't closed it

**Comment by DeckardCainRPC** [comment]
on the other hand, a user in a Sea Fort run asked me if Epoch Guardian's Q3 should pierce Spell Immunity or not. my opinion on it is that it should be blocked by Spell Immunity even though it's a Pure autoattack orb, because Arcane Orb (Outworld Devourer's Q, the Dota ability it's ostensibly based on) does *not* pierce BKB. so let that further illustrate my position on these issues - consistency, both within RPC's native effects and in their Dota counterparts, is key.

i think the only potential issue with Epoch Guardian's Q3/arcana Q3 would be if they're incorrectly draining mana when attacking Spell Immune units, but i don't think that's the case.

**Comment by ChalkyBrush** [comment]
adjusted pulverizer to target magic immunes
