### ISSUE TITLE
cant save after 150mins game

### ISSUE THREAD

**Issue by Nazolin** [ChalkyBrush/roshpit-bug-tracker#577]
what a shit bug pls fix this

**Comment by DeckardCainRPC** [comment]
you have provided no information about this issue. we have no idea what you're talking about. there is a reason that people give important information when reporting a bug, and that's because we need to understand the problem in order to try to fix it.

if you don't understand that simple truth, then you're going to continue to have a hard time.

**Comment by StillStealSteel** [comment]
I trully believe this is just random bug with oracle/smith that sometimes unable to respond on request (rare bug novadays, at least fo me). And it is not related to any time that game last.
@Nazolin closed for now, if only you can prove and play another 150min game for it.

**Comment by redledcat** [comment]
I just saw screenshot of 500+ minutes game with normal FPS and working oracle.
