### ISSUE TITLE
Red General Arcana R1 rune not working

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#58]
R1 does not deal post damage mitigation to enemies at all.
I've tried both R skill and Q3 cast land point, neither does any amplified damage as the description says.
![20171020121644_1](https://user-images.githubusercontent.com/32886049/31831809-c6422528-b592-11e7-8e67-db8428d49284.jpg)

**Comment by StillStealSteel** [comment]
Can anyone else confirm this?
If no - will try(or check code later) it later.
Dragon working on the red general rework , so it is not so important i think.

**Comment by redledcat** [comment]
Tested so far, damage do not changes on dummy.
(And steadfast units seems to not feel the difference in damage too)
Also: why damage so low? It deals 100% of my damage instead of 600% on lvl4 ulti.
![20171020213720_1](https://user-images.githubusercontent.com/32621322/31836808-d287643a-b5d6-11e7-813f-fe834bb2d881.jpg)
In arcana_ability file 
if a_d_level > 0 then
					Events.GameMasterAbility:ApplyDataDrivenModifier(Events.GameMaster, caster, "modifier_general_postmitigation", {duration = 0.3})
					local amp = 15*a_d_level
					caster:SetModifierStackCount("modifier_general_postmitigation", Events.GameMaster, amp)
could be duration 0.3 be the reason?

**Comment by redledcat** [comment]
Dragon fixed that in test version, it will work after Axe rework.

**Comment by StillStealSteel** [comment]
Lets wait for Dragon's rework patch, then i will close if he really fixed it.

**Comment by redledcat** [comment]
Works in test version

**Comment by ChalkyBrush** [comment]
Fixed in Dragon axe rework
