### ISSUE TITLE
DK'S E4 says it reduces armor, but doesn't say how much

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#596]
it says it does damage equal to 100% of E1 per rank (20x at rank 20), but it doesn't list a value for the armor shred effect at all. i would look at the code myself but, as all of you know, i'm a useless dumbass who eats rocks out of my driveway

ADDENDUM: i noticed during gameplay that it doesn't appear to reduce armor at all; the only armor shred effect i saw on targets was from W3

**Comment by StillStealSteel** [comment]
I think before some patch (year or more ago) it has numbers of how much armor it shreds. But armor reduction was so low about -300 armor at 20 runes. And because dk almost didn't change his abilities, and there is a lot of legacy code (some  copy-paste of chunks of code from different sources) i think chulky just removes this outdated armor shred and just forgot to change description. No history about this on github i think because repository only last ~1 year.

**Comment by ChalkyBrush** [comment]
fixed
