### ISSUE TITLE
Skills damage based on mana, but mana pool capped at 65k

### ISSUE THREAD

**Issue by OlDor** [ChalkyBrush/roshpit-bug-tracker#628]
Some heroes' skills damage is based on `max mana` or `current mana`, but mana pool is always capped at 65k. 
`Bahamut` W, `Epoch Guardian` Q and W, `Sorceress` W.
It is much harder to build these heroes, because they rely heavily on runes, not stats...

Are there any possible fixes to that?
Maybe link these skills' damage to Intelligence instead of `max mana`? (i.e. 1 Int = 12 or 15 mana)
And instead of `current mana` we can use: Intelligence * (current mana / max mana)

**Comment by StillStealSteel** [comment]
It's not capped at 65k. It's dota UI that can show only 65k.
Closed.
For more info go ask on discord channel where you wrong and where to find you current max mana.

I actually checked all your "bug" reports. And they all was wrong because you don't understand how some things in RPC works. Please go to discord channel and ask people to help you understand how some mechanics works. Thank you.
