### ISSUE TITLE
Sturdy Centaur Horns takes priority over Chernobog's active W

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#692]
what it does now is, if he toggles W on, he still only has 15% Steadfast. he should be able to toggle W on to have better Steadfast, at the cost of losing 1 hp every 0.03 seconds and he can't do anything about it

**Comment by DeckardCainRPC** [comment]
@Nintai did you or somebody else fix this recently?

**Comment by Nintai** [comment]
Didnt do anything here. I remember looking into code, but couldnt find a cause for it, since even if one comes before the other, it should not affect each other
lets say u would take 100% of life as dmg
-> W first to 3%
-> Centaur horn cant reduce because its not > 15%

-> centaur horn first to 15%
-> W reduces to 3%

Thats why this bug doesnt make sense 😂

**Comment by DeckardCainRPC** [comment]
i was probably fighting monsters that had multiple damage instances per attack, AND global damage amp from Pit 7 / Sea Fortress or some shit. thanks

**Comment by Nintai** [comment]
Sea Fortress is the only map with post mitigation for enemies, that work on cherno W (and ONLY cherno W)

So if normally u take 3% of life dmg, and he has true strike, it will be 6%
this will be increased by 300% so its 24%
then centaur horn will reduce it to 15% ;)
