### ISSUE TITLE
Earthshakers in Tanari hard fire path

### ISSUE THREAD

**Issue by SilentC** [ChalkyBrush/roshpit-bug-tracker#76]
I wouldn't say this is a bug, but it is extremely frustrating.
Very few heroes can push the last Earthshaker miniboss in the first teleport path. Needs way too much skill spam way too fast and it is frustrating beyond words.

Please fix this.

**Comment by redledcat** [comment]
Well, probably it is a bug. It was way easier on Spirit Zones release, and now many players complain about how long that fight is. 
The thing is, he returns on stone floor even if he was already in lava technically.
Personally I found one half-working point on 10° of circle, which works more frequent, but tries to push him over the platform in other places return him back.

**Comment by SilentC** [comment]
![20171021165141_1](https://user-images.githubusercontent.com/32886049/31900596-00518342-b7ed-11e7-8fa5-45cbf8689abd.jpg)
This annoying ES

**Comment by ChalkyBrush** [comment]
It's supposed to be difficult when soloing! However I have marginally increased his push speed

**Comment by redledcat** [comment]
Some heroes just can't push big one from the enge with their skillset.
like here I've tried to push big bully for solid 7 minutes, then finished rest of the map, returned to the lava room with my teammate trapper and spent another 7 minutes trying to push that bitch in lava.
I'm rarely being so pissed of like I am right now, because there is no matter of skill, damage or time, or surface spots which can actually help with him, and no way to push ult with most of heroes.
BUT THANKFULLY I know the magic of OBS which makes that cow surrender each time I trying to capture 10 minutes marathon of kicking him into invisible wall.
https://www.youtube.com/watch?v=HMR4DKAb-Wo
Here we have 2 heroes which simultaneously damage him with following:
1)Zhonik Q
2)Zhonik arcana E2
3)Zhonik W and W1
4)Trapper Q
5)Trapper Q1
6)Trapper autoattacks
Rarely:
7)Trapper Q2
8)Trapper E2.
IS THAT NOT ENOUGH
