### ISSUE TITLE
paladin suicides on attacking

### ISSUE THREAD

**Issue by ezlf** [ChalkyBrush/roshpit-bug-tracker#762]
so yesterday i created a new paladin, at 1st everything is fine, but later on in the game, whenever i attack anything, i die, the problem still persist today

**Comment by Nintai** [comment]
You probably have Monkey paw equipped, right?
So whenever u attack an enemy u get a stack of shield with Q3, which breaks instantly because of the 1 dmg u take from monkey paw, but since u are the one destroying it, u are the one taking the dmg ;)

but its true that it says "enemies", will fix it :D

**Comment by ezlf** [comment]
ahhhh.. now i remembered that this happened after i equipped Monkey paw xD, thank you~
