### ISSUE TITLE
Disapearing items on relog after a leggit save

### ISSUE THREAD

**Issue by triplepkush** [ChalkyBrush/roshpit-bug-tracker#826]
Well the descrription says it all the first time an arcana disapeared i didnt made a case of it but now that i used two in synthesys and saved with the item in my pool and log back in to find out my new arcana and the 2 old has vanished as well as the synthesys material i guess you wont give me back my items even if i have the premium pass but FFS do something so it dont happen anymore :-1:

**Comment by triplepkush** [comment]
Already happened after a reroll in blacksmith too but the cool thing its that it was a low tier immortal...

**Comment by DeckardCainRPC** [comment]
this (serious) issue hasn't been touched in 5 days, and i believe it's because you didn't provide information that would help us reproduce the issue. can you at least post a link to your profile on roshpit.ca? additionally, if you're feeling extra helpful, provide the steps you took, in the order in which you took them, to the best of your recollection.

if we have no idea who you are or what you did, then essentially you're asking us to dig through the entire fucking game code and just GUESS what went wrong, and i'm sure you'll agree that's not an ideal position to start in. imagine if i walked into your Starbucks and yelled "MY DICK FELL OFF AND I BET YOU WON'T GIVE ME BACK MY ITEMS NO MATTER HOW MUCH MONEY I'VE SPENT." well if we'd been having multiple reports of dick separation, then maybe we'd understand that bit at the end about 

> FFS do something so it dont happen anymore :-1:

but we don't. you can even check the bug tracker for yourself. you're the only guy who appears to have had this item loss issue, and yet you're acting like this is a chronic and well-known issue that we've neglected to address. so back to the hypothetical Starbucks scenario, you'd be back there behind the counter going "???" which is exactly what all of us are doing. we are sympathetic about your dick falling off but we obviously, *obviously* need the answers to some questions before we can start helping you with that.

**Comment by triplepkush** [comment]
Why you sound so butthurt? OBIOUSLY i am stating that items often vanish in this game if im the only one thse event ever happened to then im the unluckiest guy on earth ... Triple_P_Kush is my in-game name i played on my paladin when it happened if i remember correctly.

________________________________
De : Deckard Cain <notifications@github.com>
Envoyé : 4 novembre 2018 23:00:41
À : ChalkyBrush/roshpit-bug-tracker
Cc : triplepkush; Author
Objet : Re: [ChalkyBrush/roshpit-bug-tracker] Disapearing items on relog after a leggit save (#826)


this (serious) issue hasn't been touched in 5 days, and i believe it's because you didn't provide information that would help us reproduce the issue. can you at least post a link to your profile on roshpit.ca? additionally, if you're feeling extra helpful, provide the steps you took, in the order in which you took them, to the best of your recollection.

if we have no idea who you are or what you did, then essentially you're asking us to dig through the entire fucking game code and just GUESS what went wrong, and i'm sure you'll agree that's not an ideal position to start in. imagine if i walked into your Starbucks and yelled "MY DICK FELL OFF AND I BET YOU WON'T GIVE ME BACK MY ITEMS NO MATTER HOW MUCH MONEY I'VE SPENT." well if we'd been having multiple reports of dick separation, then maybe we'd understand that bit at the end about

FFS do something so it dont happen anymore 👎

but we don't. you can even check the bug tracker for yourself. you're the only guy who appears to have had this item loss issue, and yet you're acting like this is a chronic and well-known issue that we've neglected to address. so back to the hypothetical Starbucks scenario, you'd be back there behind the counter going "???" which is exactly what all of us are doing. we are sympathetic about your dick falling off but we obviously, obviously need the answers to some questions before we can start helping you with that.
