### ISSUE TITLE
New TP UI

### ISSUE THREAD

**Issue by redledcat** [ChalkyBrush/roshpit-bug-tracker#865]
![20181120140641_1](https://user-images.githubusercontent.com/32621322/48769990-243a0380-ecce-11e8-8568-b682bea19e37.jpg)

**Comment by ChalkyBrush** [comment]
i can probably hide htis no problem, will do

**Comment by DeckardCainRPC** [comment]
real talk, of all the changes, this pisses me off the most, because i straight up always put my tp scroll or BoTs in slot 4, so my muscle memory is to double-tap 4 to quickly gtfo. now i literally can not put a fucking tp scroll in slot 4 so i was caught in the following dilemma:

1) rebind slot 4 to Z key, rebind TP to 4 key. this would mean i could TP out of things as fast as possible... until i got BoTs, at which point i'd fuck up and double-tap the scroll, needlessly extending my TP cooldown because volvo
2) rebind TP to Z key. this would mean all of my sneaky escape attempts throughout 80% of my dota match time would be spent frantically blasting my 4 key until i remembered it's Z now. the only way to resolve this would be to purchase BoTs, and to reduce frustration, i would want to buy it as early as possible, which is a terrible idea because that's 2.5k gold spent on something that does not make me kill better, farm quicker, or die less.

between this sinister horseshit and the fact that the quality of Dota's English tooltips have been in decline for 2 years, my soul will never find peace. (Holy Locket's tooltip says "health and regeneration you *provided*." PROVIDED. as in past-tense. jesus fucking christ.)

**Comment by ChalkyBrush** [comment]
fixed
