### ISSUE TITLE
It's 2018 and Elemental Warlord's weapons can't roll any R runes

### ISSUE THREAD

**Issue by DeckardCainRPC** [ChalkyBrush/roshpit-bug-tracker#891]

**Comment by redledcat** [comment]
and many other unreasonably missing runes for many other chars
https://roshpit.wikia.com/wiki/Available_runes_on_weapons

**Comment by ChalkyBrush** [comment]
ok going to try get to this one tonight shouldn't take long

**Comment by DeckardCainRPC** [comment]
AVIABLE???

jesus christ, move that article to "*Available* runes on weapons" instead. i remember Dark started that wiki with some other dude, and neither of them could spell worth a fuck, so i'm sure it was their fault

**Comment by redledcat** [comment]
It's only my fault, and thanks for noticing
I'm slightly improved my skills in English, but "avail" apparently was too difficult verb for me
(total list of people who did at least an edit:
 me (creator) 3064 edits, 
Dark (made some weird shit builds and then left because got bored) 35 edits,
 Davi (which did enourmously great work making templates for nearly everything we needed, and even more) 714 edits,
 Deckard Cain (loremaster) 56 edits.)

**Comment by redledcat** [comment]
why the f nobody said that to me before, that page exists for eternity, and nobody cared to emphasize it

**Comment by DeckardCainRPC** [comment]
i am very sorry. you are a good boy

... i made more edits than Dark? wow i'm a big nerd

**Comment by DeckardCainRPC** [comment]
3.8b HYPE
