### ISSUE TITLE
Paladin

### ISSUE THREAD

**Issue by calltobat9** [ChalkyBrush/roshpit-bug-tracker#932]
R3-(Holy Bolt"Pure Damage")Does not attack a target with immunity to magic!

**Comment by redledcat** [comment]
pure damage != pierce spell immunity

**Comment by redledcat** [comment]
https://dota2.gamepedia.com/Spell_immunity/Enemy_Interactions
read this page please, there are a lot of physical and pure spells in dota 2 which do not pierce spell immunity

**Comment by calltobat9** [comment]
> https://dota2.gamepedia.com/Spell_immunity/Enemy_Interactions
> read this page please, there are a lot of physical and pure spells in dota 2 which do not pierce spell immunity

if so, then let them do the correct description of the skill, as there are heroes with similar spells and their damage passes through immunity to magic! I would put the question under consideration to change this hero's type of damage from magic to pure(ArcaneW) (since it's not a cheap build on hero)

**Comment by redledcat** [comment]
@ChalkyBrush is it possible to add good-looking line to the tooltips, which would say if spell does not pierce spell immunity? (There is no need to say in most cases if spell DOES pierce, but missing line which would say it DOESN'T makes people complain over and over).
Otherwise I can just add sentence "Does not pierce spell immune enemies." to all needed abilities.
Maybe it's possible to impelement it the way like elements implemented, I can go through npc files for abilities and runes.

**Comment by ChalkyBrush** [comment]
There is a way to do it in NPC files.

**Comment by redledcat** [comment]
@ChalkyBrush reminding you about "Pierces Spell Immunity: YES" key values for runes

**Comment by redledcat** [comment]
I guess I have to learn it eventually but since there is no issue I'm closing it and forgetting it forever
